apiVersion: v1
kind: Pod
metadata:
  name: idcard-app-pod
  labels:
    app: spring-web
spec:
  containers:
    - name: web-server
      # This tells Kubernetes to use the Dockerfile image we build
      image: custom-web-server-image:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8443
        - containerPort: 2222
        - containerPort: 8080
    - name: mysql-database
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Hello@123"
        - name: MYSQL_DATABASE
          value: "A-Soeng_Prakbormey-db"
      ports:
        - containerPort: 3306
