spring.application.name=idcard-management
server.port=8081
spring.datasource.url=jdbc:mysql://mysql-database:3306/A-Soeng_Prakbormey-db
spring.datasource.username=root
spring.datasource.password=Hello@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true