spring.application.name=idcard-management
spring.datasource.url=jdbc:mysql://localhost:3306/idcard_db
spring.datasource.username=root
spring.datasource.password=queen2624#$%meymey

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true